/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries to ensure a clean state
  await knex('products').del();

  await knex('products').insert([
    // STETHOSCOPES
    { id: "steth-littmann-classic", name: "Classic Acoustic Stethoscope", category: "Stethoscopes", sku: "EMS-STETH-CLASSIC", price: 109, description: "Everyday acoustic performance for EMTs and students. Tunable diaphragm, reliable build, and field-ready comfort.", image_url: "https://media.istockphoto.com/id/1348004602/photo/red-medical-stethoscope-and-bell-on-red-background-medical-service-appointment.jpg?s=612x612&w=0&k=20&c=-iVDAO5BXJotqwTJ5gXkpD7y-gBMph7CCHCEHymjj8M=" },
    { id: "steth-electronic", name: "Electronic Noise-Reducing Stethoscope", category: "Stethoscopes", sku: "EMS-STETH-ELECTRO", price: 289, description: "Electronic stethoscope with active noise reduction to cut through sirens and engine noise in the field.", image_url: "https://media.istockphoto.com/id/1285018002/photo/diabetic-measurement-tools-and-insulin-pen-on-table.jpg?s=612x612&w=0&k=20&c=bz1-Y413zzoyTFM4Rd6qQJcTOzeWyCGJVRAXqE5DwS0=" },
    { id: "steth-cardiology-pro", name: "Cardiology Pro Stethoscope", category: "Stethoscopes", sku: "EMS-STETH-CARDIO", price: 199, description: "Advanced stethoscope designed for detailed cardiac assessment. Superior acoustics with lightweight, ergonomic design.", image_url: "https://media.istockphoto.com/id/1091130498/photo/pulse-trace-and-stethoscope.jpg?s=612x612&w=0&k=20&c=MEtVyeQZQauAP4jYgto1V2FUPimEqVI3jQFGaFpgc3g=" },
    { id: "steth-universal-pro", name: "Universal Pro Stethoscope", category: "Stethoscopes", sku: "EMS-STETH-UNIVERSAL", price: 149, description: "All-purpose stethoscope for any environment. Balanced acoustics, durability, and comfort for extended use.", image_url: "https://media.istockphoto.com/id/474219539/photo/digital-tablet-and-stethoscope-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=w4ZFdM-2RsYp_9VpsYPJojIFmQafrIUQQdrJWeq771g=" },
    { id: "steth-lightweight-student", name: "Lightweight Student Stethoscope", category: "Stethoscopes", sku: "EMS-STETH-STUDENT", price: 69, description: "Affordable, lightweight stethoscope ideal for skills labs, clinicals, and early ride-alongs.", image_url: "https://media.istockphoto.com/id/1155553594/photo/a-female-healthcare-professional-taking-a-reading-using-a-stethoscope-and-carefully-listening.jpg?s=612x612&w=0&k=20&c=dEBySxJgDiPdphMWzCH9rgnrXa4q8SKmRYK2v_BCrKY=" },
    { id: "steth-rig-duty", name: "Rig-Duty Hybrid Stethoscope", category: "Stethoscopes", sku: "EMS-STETH-RIG", price: 159, description: "Hybrid acoustic design tuned for use in ambulances and helicopters with improved isolation.", image_url: "https://media.istockphoto.com/id/183361669/photo/botanist-examining-a-plant.jpg?s=612x612&w=0&k=20&c=JYXx6eMuY_sbB73XJ92ae27t1xiUr2E0d31HKFy3BTY=" },

    // KITS
    { id: "kit-student-starter", name: "EMT / Paramedic Student Starter Kit", category: "Kits", sku: "EMS-KIT-STUDENT", price: 59, description: "Starter kit aligned with EMT and paramedic coursework: shears, penlight, tape, pupil gauge, and pocket tools.", image_url: "https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=1200&q=80" },
    { id: "pack-response-backpack", name: "Rapid Response Jump Backpack", category: "Kits", sku: "EMS-PACK-JUMP", price: 189, description: "Modular EMS backpack with internal organizers for airways, IV, and trauma gear. Built for first-due rigs.", image_url: "https://media.istockphoto.com/id/2248428896/photo/extra-large-tactical-sanitary-rescue-backpack.jpg?s=612x612&w=0&k=20&c=qqvxOP4Z4b45cXwFon5UzxU5FVBoZIOl8GAmTGgUTgQ=" },
    { id: "kit-als-airway-roll", name: "ALS Airway Roll Kit", category: "Kits", sku: "EMS-KIT-ALS-AIRWAY", price: 129, description: "Roll-out airway kit with compartments for BVM, OPAs, NPAs, supraglottic devices, and adjuncts.", image_url: "https://media.istockphoto.com/id/1461631711/photo/screwdriver-with-replaceable-bits.jpg?s=612x612&w=0&k=20&c=K38pvGYuY1rFSrUmmIpUoH1Nz3LiKTW00rAuMiZ6DPA=" },
    { id: "kit-mci-triage", name: "MCI Triage & Tag Kit", category: "Kits", sku: "EMS-KIT-MCI", price: 149, description: "Mass-casualty triage kit with tags, tape, and tools for rapid START/JumpSTART triage.", image_url: "https://media.istockphoto.com/id/952119162/photo/medical-supplies.jpg?s=612x612&w=0&k=20&c=FFQiImGoXIZFd_5o7e46TBXzPKgIL-vPo42yO2JLaEM=" },
    { id: "kit-clinic-diagnostic", name: "Clinic Diagnostic Kit", category: "Kits", sku: "EMS-KIT-CLINIC", price: 99, description: "Station-side diagnostic kit with BP cuff, otoscope, reflex hammer, and thermometer case.", image_url: "https://media.istockphoto.com/id/477984136/vector/first-aid-kit.jpg?s=612x612&w=0&k=20&c=zfKTAwJ6RVhOpvMGKOeTJ6_GyYDXOjwUBNxNZ_17Q1M=" },

    // APPAREL
    { id: "pants-5in1-tactical", name: "5-in-1 Tactical EMS Pants", category: "Apparel", sku: "EMS-PANTS-5IN1", price: 79, description: "Reinforced tactical pants with shears, radio, and glove pockets. Built for long shifts and rough calls.", image_url: "https://media.istockphoto.com/id/1446081026/photo/a-soldier-a-tactical-medic-opens-a-first-aid-kit-close-up-view.jpg?s=612x612&w=0&k=20&c=ed__scBcEWjLPggF2hnjRVDXZpfWGvISYyAocMTH2ho=" },
    { id: "pants-milspec-cargo", name: "Mil‑Spec 8‑Pocket Cargo Pants", category: "Apparel", sku: "EMS-PANTS-MILSPEC", price: 89, description: "Military-inspired EMS pants with 8 functional pockets for shears, gloves, markers, and diagnostic tools.", image_url: "https://media.istockphoto.com/id/173559155/photo/casual-wear.jpg?s=612x612&w=0&k=20&c=d7EmtBKQfdigGXe-JA-IYFk5lIkpYxJTqX7Fs-hX7cI=" },
    { id: "pants-rugged-rig", name: "Rugged Rig Cargo Pants", category: "Apparel", sku: "EMS-PANTS-RIG", price: 99, description: "Heavy-duty, rig-ready pants with reinforced seams and 7 multi-depth pockets for tools and supplies.", image_url: "https://media.istockphoto.com/id/618546958/photo/man-climbing-a-ladder.jpg?s=612x612&w=0&k=20&c=CsdimmNLuDJzj45k_n0R2_7ekO1hhAmh-6ffpywAHls=" },
    { id: "pants-lightweight-duty", name: "Lightweight Duty BDU Pants", category: "Apparel", sku: "EMS-PANTS-LW-BDU", price: 69, description: "Breathable, lightweight BDU‑style pants with 6 pockets, ideal for hot climates and busy summer shifts.", image_url: "https://media.istockphoto.com/id/468832278/photo/police-officer-using-speed-gun.jpg?s=612x612&w=0&k=20&c=Nuiy1KxfdmmhjQPMmWU3RG0urhSafAdpcWKV8-5jQNk=" },
    { id: "pants-winter-softshell", name: "Winter Softshell EMS Pants", category: "Apparel", sku: "EMS-PANTS-WINTER", price: 119, description: "Fleece-lined softshell EMS pants with 5 zipped pockets to secure gear during cold, wet calls.", image_url: "https://media.istockphoto.com/id/91099607/photo/snowshoeing-adventure.jpg?s=612x612&w=0&k=20&c=sBvSoB8t0AVFxU7Dc_mxO76NNSzBM8zEv14zT2FNW1Q=" },
    { id: "shorts-cargo-duty", name: "Cargo Duty Shorts (Station Use)", category: "Apparel", sku: "EMS-SHORTS-CARGO", price: 54, description: "Multi-pocket duty shorts for station and training days, with 6 pockets and reinforced seat.", image_url: "https://media.istockphoto.com/id/1430594504/photo/mens-shorts-isolated.jpg?s=612x612&w=0&k=20&c=IvJ9va1uC8CptZpBzWja3IGTq3_gbaUpTRNd9yK5AOY=" },

    // TOOLS
    { id: "tool-shears-ballistic", name: "Ballistic-Rated Trauma Shears", category: "Tools", sku: "EMS-TOOL-SHEARS", price: 19, description: "Hardened trauma shears designed to cut denim, leather, and seatbelts without losing edge.", image_url: "https://media.istockphoto.com/id/2238279585/photo/creative-contemporary-collage-scissors-cutting-chain-link-symbolizing-fragile-rebellion-and.jpg?s=612x612&w=0&k=20&c=2Aqc_dpf4ILAibYLjSME0esv1qiP5KHI_KxNiQCWxKk=" },
    { id: "tool-rescue-multitool", name: "Responder Rescue Multitool", category: "Tools", sku: "EMS-TOOL-MULTI", price: 49, description: "Folding rescue multitool with seatbelt cutter, oxygen key, glass punch, and utility blade.", image_url: "https://media.istockphoto.com/id/1452469768/photo/disaster-supply-kit-for-earthquake-on-black-wooden-table-flat-lay.jpg?s=612x612&w=0&k=20&c=ql1dRG2j9HvOw5w9q6UIX7EZK7gbiMkJPMlMsd8X_rg=" },
    { id: "tool-window-punch", name: "Spring-Loaded Window Punch", category: "Tools", sku: "EMS-TOOL-PUNCH", price: 15, description: "One-handed, spring-loaded center punch for rapid tempered glass access during vehicle extrication.", image_url: "https://media.istockphoto.com/id/1273900646/photo/new-awl-with-red-handle-cut-out-on-the-hand.jpg?s=612x612&w=0&k=20&c=xzIRaXhpEfO9XOaTYkvLmYzteIut0GnLBalwwhxcT1M=" },
    { id: "tool-penlight-led", name: "LED Pupil Penlight", category: "Tools", sku: "EMS-TOOL-PENLIGHT", price: 12, description: "Aluminum penlight with pupil gauge printing for neuro checks and general assessments.", image_url: "https://media.istockphoto.com/id/1180949169/photo/led-metal-tactical-flashlight-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=fe-Hx91mniEXNBxglMfqZPa3BflSN_D2DSZhDIFNQO8=" },
    { id: "tool-tourniquet-combat", name: "Combat-Ready Tourniquet", category: "Tools", sku: "EMS-TOOL-TQ", price: 35, description: "Windlass-style tourniquet with time label for rapid extremity hemorrhage control.", image_url: "https://media.istockphoto.com/id/1130302444/photo/person-in-black-medical-gloves-applies-the-tourniquet-to-his-hand-to-prevent-bleeding-during.jpg?s=612x612&w=0&k=20&c=9GHA2jpOwj7dKZlwmetKcYEFi42Fv1m4B8N8D5hW75A=" }
  ]);
};